language: ruby
cache: bundler
script:
  - bundle exec rake spec
  - bundle exec rake cucumber
rvm:
  - 2.0.0
notifications:
    irc: "chat.freenode.com#refugerestrooms"
    skip_join: true
    template:
      - "Build #%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
