development:
  adapter: postgresql
  encoding: unicode
  database: restrooms_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: restrooms_test
  pool: 5
  host: localhost
