#!/bin/bash
set -e

if [[ -z ${SKIP_CREATE_DB+x} ]]; then
  # Set up the database for development, and seed with placeholder data from `db/export.csv`
  SEEDING_DONT_GEOCODE="true" rails db:setup
fi

exec "$@"
